/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragapult-7c04d0b88b8e4c2b873f4545b78bc8f4
Title: Dragapult
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from '../assets/3d/animation2.glb'

const ContactAnimal = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="animation2glb">
          <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <skinnedMesh
              name="girl_body"
              geometry={nodes.girl_body.geometry}
              material={materials["skin color.001"]}
              skeleton={nodes.girl_body.skeleton}
            />
            <skinnedMesh
              name="hair_base"
              geometry={nodes.hair_base.geometry}
              material={materials["hair base color"]}
              skeleton={nodes.hair_base.skeleton}
            />
            <skinnedMesh
              name="shirt"
              geometry={nodes.shirt.geometry}
              material={materials["shirt color"]}
              skeleton={nodes.shirt.skeleton}
            />
            <skinnedMesh
              name="shoes"
              geometry={nodes.shoes.geometry}
              material={materials["shoe color"]}
              skeleton={nodes.shoes.skeleton}
            />
            <skinnedMesh
              name="trouser"
              geometry={nodes.trouser.geometry}
              material={materials["trouser color"]}
              skeleton={nodes.trouser.skeleton}
            />
            <skinnedMesh
              name="tummy_cloth"
              geometry={nodes.tummy_cloth.geometry}
              material={materials["tummycloth color"]}
              skeleton={nodes.tummy_cloth.skeleton}
            />
            <primitive object={nodes.mixamorigHips} />
          </group>
        </group>
        <group name="AmbientLight" />
        <directionalLight
          name="DirectionalLight"
          intensity={2}
          decay={2}
          position={[5, 10, 7.5]}
        >
          <group position={[0, 0, -1]} />
        </directionalLight>
        <group name="HemisphereLight" position={[0, 10, 0]} />
        <pointLight name="PointLight" intensity={1} decay={2} />
      </group>
    </group>
  );
}

export default ContactAnimal