/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragapult-7c04d0b88b8e4c2b873f4545b78bc8f4
Title: Dragapult
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useContactAnimalGLTF } from "../components/SharedGlb";

// import { useContactAnimalGLTF } from "./components/SharedGlb";
// import scene from '../assets/3d/6.glb'

const ContactAnimal = ({ currentAnimation, ...props }) => {
  const group = useRef();
  // const { nodes, materials, animations } = useGLTF(scene);
  const { nodes, materials, animations } = useContactAnimalGLTF();
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="girlglb">
          <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <skinnedMesh
              name="body"
              geometry={nodes.body.geometry}
              material={materials["skin color"]}
              skeleton={nodes.body.skeleton}
            />
            <skinnedMesh
              name="hair_base"
              geometry={nodes.hair_base.geometry}
              material={materials["hair color"]}
              skeleton={nodes.hair_base.skeleton}
            />
            <skinnedMesh
              name="shirt"
              geometry={nodes.shirt.geometry}
              material={materials["shirt color"]}
              skeleton={nodes.shirt.skeleton}
            />
            <skinnedMesh
              name="shoes"
              geometry={nodes.shoes.geometry}
              material={materials["light hair color "]}
              skeleton={nodes.shoes.skeleton}
            />
            <skinnedMesh
              name="trouser"
              geometry={nodes.trouser.geometry}
              material={materials["trouser color"]}
              skeleton={nodes.trouser.skeleton}
            />
            <primitive object={nodes.mixamorigHips} />
          </group>
        </group>
      </group>
    </group>
  );
}

export default ContactAnimal