/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ivan Norman (https://sketchfab.com/vanidza)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-girl-a4bf221f620e49f8bc7af53e6d6a4f3c
Title: Cartoon girl
*/

import { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import girlScene from "../assets/3d/purple.glb";

const Girl = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const girlRef = useRef();

  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(girlScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;

    lastX.current = clientX;
  }

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;
      girlRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }

  const handleKeyDown = (e) => {
    if (e.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);
      girlRef.current.rotation.y -= 0.01 * Math.PI;
      rotationSpeed.current = 0.0125;
    } else if (e.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);
      girlRef.current.rotation.y += 0.01 * Math.PI;
      rotationSpeed.current = -0.0125;
    }
  }

  const handleKeyUp = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      girlRef.current.rotation.y += rotationSpeed.current;

    } else {
      const rotation = girlRef.current.rotation.y;

      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */

      const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the girl's orientation
      switch (true) {
        case normalizedRotation >= 0.7 && normalizedRotation <= 1.7:
          setCurrentStage(1);
          break;
        case normalizedRotation >= 2.3 && normalizedRotation <= 3.3:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 3.8 && normalizedRotation <= 4.8:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 5.3 && normalizedRotation <= 5.8:
          setCurrentStage(4);
        default:
          setCurrentStage(null);
      }
    }
  })

  // autorotation
  useFrame(() => {
    const autoRotationSpeed = 0.002; // Adjust the speed of auto-rotation as needed
    girlRef.current.rotation.y += autoRotationSpeed;

    const rotation = girlRef.current.rotation.y;
    const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    // Set the current stage based on the girl's orientation
    switch (true) {
      case normalizedRotation >= 0.7 && normalizedRotation <= 1.7:
        setCurrentStage(1);
        break;
      case normalizedRotation >= 2.3 && normalizedRotation <= 3.3:
        setCurrentStage(2);
        break;
      case normalizedRotation >= 3.8 && normalizedRotation <= 4.8:
        setCurrentStage(3);
        break;
      case normalizedRotation >= 5.3 && normalizedRotation <= 5.8:
        setCurrentStage(4);
        break;
      default:
        setCurrentStage(null);
    }
  })

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);
    }

  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

  return (
    <a.group ref={girlRef} {...props}>
      <directionalLight
        intensity={2}
        decay={2}
        position={[1.424, 5.401, 7.5]}
      />
      <pointLight intensity={2} decay={2} position={[-0.919, 0, 0]} />

      {/* <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Girl}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.right_eye.geometry}
        material={materials["eye ball color"]}
        position={[0.189, 1.146, 0.215]}
        scale={0.081}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.left_eye.geometry}
        material={materials["eye ball"]}
        position={[-0.175, 1.146, 0.215]}
        scale={0.081}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.right_pupil.geometry}
        material={materials.pupil}
        position={[0.191, 1.133, 0.249]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.059, 0.062, 0.058]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.left_pupil.geometry}
        material={materials["pupil.003"]}
        position={[-0.179, 1.133, 0.249]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.059, 0.062, 0.058]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.left_eyebrow_curved.geometry}
        material={materials["eyebrow.005"]}
        position={[-0.289, 1.231, 0.231]}
        rotation={[1.641, 0.127, -1.234]}
        scale={[0.012, 0.053, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.righteyebrow_curved001.geometry}
        material={materials["eyebrow.007"]}
        position={[0.297, 1.248, 0.227]}
        rotation={[-1.644, 0.117, 1.954]}
        scale={[0.012, 0.053, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leftsmall_pupil.geometry}
        material={materials["pupil.004"]}
        position={[-0.178, 1.127, 0.27]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.044, 0.046, 0.043]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.right_small_pupil.geometry}
        material={materials["pupil.006"]}
        position={[0.191, 1.127, 0.27]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.044, 0.046, 0.043]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.eyelash001.geometry}
        material={materials.eyelash}
        position={[0.321, 1.186, 0.193]}
        rotation={[-0.249, 0.128, -1.181]}
        scale={[0.009, 0.016, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.eyelash004.geometry}
        material={materials["eyelash.001"]}
        position={[0.308, 1.191, 0.204]}
        rotation={[-0.275, -0.449, -1.335]}
        scale={[0.009, 0.014, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.eyelash003.geometry}
        material={materials["eyelash.002"]}
        position={[0.297, 1.191, 0.21]}
        rotation={[-0.249, -0.79, -1.299]}
        scale={[0.007, 0.012, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.right_eye_lied.geometry}
        material={materials.eyelid}
        position={[0.229, 1.192, 0.263]}
        rotation={[-0.015, 0.415, -1.576]}
        scale={[0.026, 0.031, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.left_eye_lid.geometry}
        material={materials["eyelid.001"]}
        position={[-0.234, 1.211, 0.252]}
        rotation={[-1.541, -0.466, 1.052]}
        scale={0.031}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.eyelash002.geometry}
        material={materials["eyelash.003"]}
        position={[-0.277, 1.188, 0.228]}
        rotation={[-2.959, -0.312, 2.078]}
        scale={[0.007, 0.012, 0.004]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.eyelash.geometry}
        material={materials["eyelash.004"]}
        position={[-0.28, 1.178, 0.212]}
        rotation={[-2.893, -0.104, 1.955]}
        scale={[0.009, 0.014, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair_base.geometry}
        material={materials.hairbase}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair.geometry}
        material={materials.hair}
        position={[0.02, 1.48, 0.337]}
        rotation={[2.633, 0.494, 1.04]}
        scale={[0.052, 0.095, 0.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair003.geometry}
        material={materials["hair.003"]}
        position={[0.194, 1.453, 0.254]}
        rotation={[0.404, -0.503, -2.504]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair004.geometry}
        material={materials["hair.004"]}
        position={[0.234, 1.467, 0.186]}
        rotation={[0.475, -0.475, -2.473]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair005.geometry}
        material={materials["hair.005"]}
        position={[0.331, 1.337, 0.086]}
        rotation={[0.159, -0.642, -3.055]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair006.geometry}
        material={materials["hair.006"]}
        position={[0.311, 1.393, 0.007]}
        rotation={[0.159, -0.642, -3.055]}
        scale={[0.06, 0.099, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair007.geometry}
        material={materials["hair.007"]}
        position={[0.332, 1.382, -0.063]}
        rotation={[0.159, -0.642, -3.055]}
        scale={[0.067, 0.111, 0.068]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair008.geometry}
        material={materials["hair.008"]}
        position={[0.362, 1.451, -0.172]}
        rotation={[0.118, -0.649, -3.122]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair009.geometry}
        material={materials["hair.020"]}
        position={[0.325, 1.44, -0.199]}
        rotation={[0.102, -0.652, 3.134]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair010.geometry}
        material={materials["hair.021"]}
        position={[0.306, 1.36, -0.218]}
        rotation={[-0.225, -0.686, 2.888]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair011.geometry}
        material={materials["hair.022"]}
        position={[0.206, 1.351, -0.18]}
        rotation={[-0.109, -0.686, 2.888]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair012.geometry}
        material={materials["hair.023"]}
        position={[0.119, 1.337, -0.174]}
        rotation={[-0.058, -0.527, 2.93]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair013.geometry}
        material={materials["hair.024"]}
        position={[0.032, 1.339, -0.186]}
        rotation={[-0.052, -0.298, 2.979]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair014.geometry}
        material={materials["hair.025"]}
        position={[-0.06, 1.343, -0.179]}
        rotation={[-0.043, -0.066, 3.021]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair015.geometry}
        material={materials["hair.026"]}
        position={[-0.115, 1.348, -0.162]}
        rotation={[-0.022, 0.338, 3.094]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair016.geometry}
        material={materials["hair.027"]}
        position={[-0.277, 1.462, -0.291]}
        rotation={[0.211, 0.921, 2.964]}
        scale={[0.081, 0.133, 0.082]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair017.geometry}
        material={materials["hair.028"]}
        position={[-0.205, 1.466, -0.283]}
        rotation={[0.381, 1.351, 2.7]}
        scale={[0.087, 0.143, 0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair018.geometry}
        material={materials["hair.029"]}
        position={[-0.175, 1.366, -0.171]}
        rotation={[-0.022, 0.338, 3.094]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair019.geometry}
        material={materials["hair.030"]}
        position={[0.169, 1.356, -0.253]}
        rotation={[-0.109, -0.686, 2.888]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair020.geometry}
        material={materials["hair.031"]}
        position={[-0.115, 1.339, -0.186]}
        rotation={[-0.052, -0.298, 2.979]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair025.geometry}
        material={materials["hair.032"]}
        position={[-0.072, 1.326, -0.205]}
        rotation={[-0.052, -0.298, 2.979]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair026.geometry}
        material={materials["hair.033"]}
        position={[0.049, 1.346, -0.246]}
        rotation={[-0.052, -0.298, 2.979]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair027.geometry}
        material={materials["hair.034"]}
        position={[0.012, 1.346, -0.289]}
        rotation={[-0.052, -0.298, 2.979]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair028.geometry}
        material={materials["hair.035"]}
        position={[-0.213, 1.445, -0.315]}
        rotation={[-0.005, 0.921, 2.964]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair029.geometry}
        material={materials["hair.036"]}
        position={[-0.121, 1.444, -0.37]}
        rotation={[-0.005, 0.921, 2.964]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair030.geometry}
        material={materials["hair.037"]}
        position={[-0.003, 1.433, -0.385]}
        rotation={[-0.035, 0.48, 2.997]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair031.geometry}
        material={materials["hair.038"]}
        position={[0.204, 1.428, -0.344]}
        rotation={[-0.032, -0.202, 2.974]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair032.geometry}
        material={materials["hair.039"]}
        position={[0.269, 1.412, -0.316]}
        rotation={[-0.032, -0.202, 2.974]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair033.geometry}
        material={materials["hair.040"]}
        position={[0.079, 1.44, -0.37]}
        rotation={[-0.061, 0.324, 3.079]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair034.geometry}
        material={materials["hair.041"]}
        position={[-0.296, 1.457, -0.215]}
        rotation={[0.211, 0.921, 2.964]}
        scale={[0.08, 0.131, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair035.geometry}
        material={materials["hair.042"]}
        position={[-0.332, 1.396, -0.131]}
        rotation={[0.449, 0.921, 2.964]}
        scale={[0.048, 0.079, 0.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair036.geometry}
        material={materials["hair.043"]}
        position={[-0.334, 1.402, -0.084]}
        rotation={[0.659, 0.921, 2.964]}
        scale={[0.048, 0.079, 0.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair038.geometry}
        material={materials["hair.045"]}
        position={[-0.348, 1.4, -0.181]}
        rotation={[0.211, 0.921, 2.964]}
        scale={[0.072, 0.118, 0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair039.geometry}
        material={materials["hair.047"]}
        position={[-0.113, 1.663, 0.175]}
        rotation={[1.925, 0.844, 1.782]}
        scale={[0.085, 0.155, 0.074]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair041.geometry}
        material={materials["hair.049"]}
        position={[-0.146, 1.597, 0.282]}
        rotation={[2.297, 0.832, 1.504]}
        scale={[0.079, 0.144, 0.069]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair042.geometry}
        material={materials["hair.050"]}
        position={[-0.089, 1.677, 0.105]}
        rotation={[2.124, 0.848, 1.679]}
        scale={[0.069, 0.126, 0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair044.geometry}
        material={materials["hair.052"]}
        position={[-0.366, 1.362, -0.054]}
        rotation={[0.53, 0.921, 2.964]}
        scale={[0.053, 0.088, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair045.geometry}
        material={materials["hair.053"]}
        position={[-0.211, 1.352, -0.205]}
        rotation={[-0.022, 0.338, 3.094]}
        scale={[0.078, 0.128, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair046.geometry}
        material={materials["hair.054"]}
        position={[-0.043, 1.662, 0.081]}
        rotation={[2.169, 0.71, 1.83]}
        scale={[0.062, 0.112, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair047.geometry}
        material={materials["hair.055"]}
        position={[-0.108, 1.697, 0.006]}
        rotation={[1.979, 0.896, 1.905]}
        scale={[0.055, 0.1, 0.048]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair048.geometry}
        material={materials["hair.061"]}
        position={[0.169, 1.501, 0.243]}
        rotation={[0.475, -0.475, -2.473]}
        scale={[0.044, 0.073, 0.045]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair049.geometry}
        material={materials["hair.062"]}
        position={[0.205, 1.504, 0.175]}
        rotation={[0.003, -0.471, -2.556]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair050.geometry}
        material={materials["hair.063"]}
        position={[0.197, 1.542, 0.137]}
        rotation={[0.003, -0.471, -2.556]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair051.geometry}
        material={materials["hair.064"]}
        position={[0.217, 1.573, 0.097]}
        rotation={[0.019, -0.471, -2.521]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair052.geometry}
        material={materials["hair.066"]}
        position={[0.208, 1.586, 0.039]}
        rotation={[-0.009, -0.471, -2.584]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair053.geometry}
        material={materials["hair.067"]}
        position={[0.256, 1.575, 0.016]}
        rotation={[-0.069, -0.466, -2.715]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair054.geometry}
        material={materials["hair.068"]}
        position={[0.317, 1.519, -0.036]}
        rotation={[-0.1, -0.461, -2.784]}
        scale={[0.053, 0.087, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair055.geometry}
        material={materials["hair.069"]}
        position={[0.247, 1.623, -0.039]}
        rotation={[0.329, -0.582, -2.761]}
        scale={[0.061, 0.101, 0.062]}
      />
      {/* <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={39.598}
        position={[0.05, 0.823, 2.754]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair056.geometry}
        material={materials["hair.070"]}
        position={[0.215, 1.638, -0.084]}
        rotation={[0.329, -0.582, -2.761]}
        scale={[0.061, 0.101, 0.062]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair057.geometry}
        material={materials["hair.071"]}
        position={[0.282, 1.462, -0.242]}
        rotation={[-0.032, -0.202, 2.974]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair058.geometry}
        material={materials["hair.072"]}
        position={[0.201, 1.507, -0.264]}
        rotation={[0.106, -0.202, 2.974]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair059.geometry}
        material={materials["hair.073"]}
        position={[0.032, 1.605, -0.237]}
        rotation={[0.46, 0.328, 2.991]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair060.geometry}
        material={materials["hair.074"]}
        position={[-0.026, 1.585, -0.255]}
        rotation={[0.451, 0.299, 2.925]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair061.geometry}
        material={materials["hair.075"]}
        position={[0.078, 1.599, -0.239]}
        rotation={[0.46, 0.328, 2.991]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair062.geometry}
        material={materials["hair.076"]}
        position={[-0.145, 1.593, -0.234]}
        rotation={[0.653, 0.862, 2.612]}
        scale={[0.074, 0.121, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair063.geometry}
        material={materials["hair.077"]}
        position={[-0.371, 1.323, -0.021]}
        rotation={[0.53, 0.921, 2.964]}
        scale={[0.053, 0.088, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair064.geometry}
        material={materials["hair.078"]}
        position={[-0.366, 1.387, 0.072]}
        rotation={[0.834, 1.145, 2.612]}
        scale={[0.053, 0.088, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair065.geometry}
        material={materials["hair.079"]}
        position={[-0.315, 1.38, 0.079]}
        rotation={[0.706, 1.145, 2.612]}
        scale={[0.053, 0.088, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair066.geometry}
        material={materials["hair.080"]}
        position={[0.337, 1.403, 0.115]}
        rotation={[0.288, -0.601, -2.834]}
        scale={[0.049, 0.08, 0.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lip.geometry}
        material={materials.lip}
        position={[0.001, 0.97, 0.262]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.053, 0.053, 0.053]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shirt.geometry}
        material={materials.cloth}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shoes.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pant.geometry}
        material={materials["trouser color"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.girl_body.geometry}
        material={materials["skin color"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.girl_mid_section.geometry}
        material={materials["mid section color"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair001.geometry}
        material={materials["hair.014"]}
        position={[-0.037, 1.499, 0.33]}
        rotation={[2.586, 0.624, 1.13]}
        scale={[0.044, 0.081, 0.039]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair002.geometry}
        material={materials["hair.015"]}
        position={[-0.127, 1.494, 0.305]}
        rotation={[2.41, 0.761, 1.404]}
        scale={[0.04, 0.073, 0.035]}
      />
    </a.group>
  );
}

export default Girl;